# Generated by Django 3.0 on 2019-12-14 14:40

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=blog.models.Post.__str__, unique=True),
        ),
    ]
